### ISSUE TITLE
问题 关于更换词库

### ISSUE THREAD

**Issue by ShanShuWu** [GC-ZF/nonebot_plugin_wordsnorote#1]
### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

纯纯萌新，想更换插件中的词库，但是一顿操作无果，想请教一下具体操作，感谢

**Comment by GC-ZF** [comment]
> ### 使用的系統？ || What operating system are you using?
> Windows
> 
> ### 问题描述 | Describe the bug
> 纯纯萌新，想更换插件中的词库，但是一顿操作无果，想请教一下具体操作，感谢
> 
> ### 出现问题的QQ | QQ
> _No response_

你要下载哪本词库？我给你看看

**Comment by ShanShuWu** [comment]
四级真题词汇   idCET4luan_1

**Comment by ShanShuWu** [comment]
四级真题词汇   idCET4luan_1

**Comment by GC-ZF** [comment]
> 四级真题词汇 idCET4luan_1

因为你没留具体的报错信息，我也不知道是什么问题，四级帮你转好了，看仓库首页说明更换词库

**Comment by ShanShuWu** [comment]
感谢，我猜我应该是在转换上操作错误了，直接更换了文件
