### ISSUE TITLE
[Bug]: Readme文档里.env打错了

### ISSUE THREAD

**Issue by ElainaFanBoy** [GC-ZF/nonebot_plugin_wordsnorote#2]
### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在.evn中配置参数说明

有点强迫症lol

**Comment by GC-ZF** [comment]
> ### 使用的系統？ || What operating system are you using?
> Windows
> 
> ### 问题描述 | Describe the bug
> 在.evn中配置参数说明
> 
> 有点强迫症lol
> 
> ### 出现问题的QQ | QQ
> _No response_

谢谢，已更改
