### ISSUE TITLE
将来可以支持每个QQ号自定义词库吗？

### ISSUE THREAD

**Issue by ElainaFanBoy** [GC-ZF/nonebot_plugin_wordsnorote#3]
将来可以支持每个QQ号自选目录下的任意词库吗，希望可以整一个乱序功能

**Comment by GC-ZF** [comment]
> 将来可以支持每个QQ号自选目录下的任意词库吗，希望可以整一个乱序功能

最近比较忙，但是有空自选词库功能可以考虑
乱序是什么乱序？这个没听懂

**Comment by ElainaFanBoy** [comment]
> > 将来可以支持每个QQ号自选目录下的任意词库吗，希望可以整一个乱序功能
> 
> 最近比较忙，但是有空自选词库功能可以考虑
> 乱序是什么乱序？这个没听懂

正常两个号从同一天开始背同一本词库的话都是序号1-20，单词也都是一样的，第二天也都是21-40，乱序就是从词库里随机抽取20个词，然后服务器本地记录下来，以后不会再抽到。（是不是不太好实现）

**Comment by GC-ZF** [comment]
> 正常两个号从同一天开始背同一本词库的话都是序号1-20，单词也都是一样的，第二天也都是21-40，乱序就是从词库里随机抽取20个词，然后服务器本地记录下来，以后不会再抽到。（是不是不太好实现）

这个功能可以实现，但是我感觉没有实际意义，两个人背互相又不影响，最后背的都是那一本书。其次3000多个单词，你每抽一个单词就要查一下有没有背过，最坏结果一个单词要查3000遍，延迟应该会相当高，所以不计划加这个功能
