### ISSUE TITLE
题外话|啊这，有个APP就叫不背单词

### ISSUE THREAD

**Issue by qjksxy** [GC-ZF/nonebot_plugin_wordsnorote#4]
我正用着这个APP背单词呢，感觉最适合我，也推荐一下
我用过扇贝、墨墨，还是这个不背单词最舒服

**Comment by GC-ZF** [comment]
> 我正用着这个APP背单词呢，感觉最适合我，也推荐一下 我用过扇贝、墨墨，还是这个不背单词最舒服

就是按那个APP取得，QQ真的比不上APP，但是朋友催了好几次了，说QQ高频点开，实在没办法写了一个，我感觉这个功能很鸡肋，肯定不会有什么人背，这种东西不管通过什么途径，都得靠自己坚持，所以叫不背单词而不是背单词，但后台下载量挺高的，还有人提新功能😂
