### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by N791** [GC-ZF/nonebot_plugin_wordsnorote#5]
### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='3', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

**Comment by GC-ZF** [comment]
> ### 使用的系統？ || What operating system are you using?
> Windows
> 
> ### 问题描述 | Describe the bug
> nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='3', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
> 
> ### 出现问题的QQ | QQ
> _No response_

报错信息太少了，麻烦复现一下问题。

检查启动bot.py时是否有错误，在群聊中发送『不背单词』，将报错截图（全屏截图，包含报错提示信息、出现错误的文件等）

可能的错误：gocq中报错：[WARNING]：转换CQ码（{"type":xxxxxx省略}），到MiraiGo Element时出现错误：encode silk failed:convert pcm file errot: exec:"ffmpeg":executa file not found in %PATH% 将忽略本段CQ码

如出现此错误，请参考 https://go-cqhttp-docs.aya1.top/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg 为电脑配置**ffmpeg**环境
