### ISSUE TITLE
[Bug]: 运行报错'PrivateMessageEvent' object has no attribute 'group_id'

### ISSUE THREAD

**Issue by LeonX86** [GC-ZF/nonebot_plugin_wordsnorote#6]
### 使用的系統？ || What operating system are you using?

Linux

### 问题描述 | Describe the bug

Python环境是3.9.1
词库是用的项目仓库里转好的考研词库，改了名字放在wordsnorote路径下
运行报错
![image](https://user-images.githubusercontent.com/49100008/212461766-88a2704c-1f94-4eef-85eb-c774353c1773.png)

**Comment by GC-ZF** [comment]
仅支持群聊，你可以自己建一个小群或者自己改下代码[#L94](https://github.com/GC-ZF/nonebot_plugin_wordsnorote/blob/e18d96c6356d87ed35e4055f29a2ce5b78d470a9/nonebot_plugin_wordsnorote/__init__.py#L94)，把group_id写成固定值。这么搞是为了合并转发消息，因为一个单词四条消息，20个单词八十条很顶聊天记录，体验不好

**Comment by GC-ZF** [comment]
> ### 使用的系統？ || What operating system are you using?
> Linux
> 
> ### 问题描述 | Describe the bug
> Python环境是3.9.1 词库是用的项目仓库里转好的考研词库，改了名字放在wordsnorote路径下 运行报错 ![image](https://user-images.githubusercontent.com/49100008/212461766-88a2704c-1f94-4eef-85eb-c774353c1773.png)
> 
> ### 出现问题的QQ | QQ
> _No response_
仅支持群聊，你可以自己建一个小群或者自己改下代码[#L94](https://github.com/GC-ZF/nonebot_plugin_wordsnorote/blob/e18d96c6356d87ed35e4055f29a2ce5b78d470a9/nonebot_plugin_wordsnorote/__init__.py#L94)，把group_id写出固定值。这么搞是为了合并转发消息，因为一个单词四条消息，20个单词八十条很顶聊天记录，体验不好

**Comment by LeonX86** [comment]
> 仅支持群聊，你可以自己建一个小群或者自己改下代码[#L94](https://github.com/GC-ZF/nonebot_plugin_wordsnorote/blob/e18d96c6356d87ed35e4055f29a2ce5b78d470a9/nonebot_plugin_wordsnorote/__init__.py#L94)，把group_id写成固定值。这么搞是为了合并转发消息，因为一个单词四条消息，20个单词八十条很顶聊天记录，体验不好

嗷嗷，群聊能正常使用哒
